name: birthday_app
description: A Flutter app to showcase birthday functionality with GIF and audio.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For playing audio
  audioplayers: any

  # Other basic dependencies, if needed
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets such as GIFs and audio files
  assets:
    - assets/birthday_cake.gif
    - assets/happy_birthday.mp3
